### PR TITLE
PXP-2441: use harakiri timeout

### PR DESCRIPTION
**Pull request by fantix**
fix(timeout): Using the new uWSGI harakiri from cdispyutils 0.2.12.

### Improvements
* Fixed inconsistent successful result when 504 Timeout

### Deployment changes
* Now uWSGI worker process will kill itself (harakiri) and restart depending on reverse proxy timeout

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
The style in this PR agrees with [`black`](https://github.com/ambv/black). :heavy_check_mark:

This formatting comment was generated automatically by a script in [uc-cdis/wool](https://github.com/uc-cdis/wool).

**Comment by PlanXCyborg** [comment]
Jenkins Build 1 : time taken 13 min
          Check the https://jenkins.planx-pla.net/job/perf-sheepdog/job/PR-261/1/display/redirect

**Comment by PlanXCyborg** [comment]
Jenkins Build 2 : time taken 19 min
          Check the https://jenkins.planx-pla.net/job/perf-sheepdog/job/PR-261/2/display/redirect

**Comment by PlanXCyborg** [comment]
Jenkins Build 3 : time taken 20 min
          Check the https://jenkins.planx-pla.net/job/perf-sheepdog/job/PR-261/3/display/redirect

**Comment by fantix** [comment]
Confirmed that the failing perofrmance pipeline shall be fixed in recent cloud-automation code, so merging now.

**Pull request merged**
