### PR TITLE
Update README.md - add postgres prerequisite

### PR DESCRIPTION
**Pull request by AlbertSnows**
also adding a small note to have postgres installed.

Link to JIRA ticket if there is one: n/a

### Improvements 
- add a bit more clarity regarding setup prereqs

### CODE REVIEW

**Comment by Avantol13** [comment]
Don't add anything in the PR description for headings where there are no updates. e.g. don't put n/a b/c that will get grabbed in release notes. Also make sure the item you do add is a bullet under the heading (not in the heading itself)

**Comment by Avantol13** [comment]
Thanks for updating the docs and making the requirements more clear :heart:

**Review by Avantol13 — APPROVED** [review]

**Review by k-burt-uch — APPROVED** [review]

**Comment by k-burt-uch** [comment]
Thanks for updating this. 

Just a heads up - our PR descriptions get automated into release notes that are externally facing. As such, there's a specific format that requires changes to be list items under the headers. 

https://github.com/uc-cdis/datastage-users/pull/1265

for example.

I went ahead and fixed it here.

**Comment by AlbertSnows** [comment]
noted, thanks

**Pull request merged**
