### PR TITLE
[WIP] feat(to-indexd): [TT-311] Moved to indexd completely

### PR DESCRIPTION
**Pull request by DrSpez**

### CODE REVIEW

**Comment by ProfOak** [comment]
The changes needed to make the tests work are in my PR.

https://github.com/uc-cdis/sheepdog/pull/85

**Comment by DrSpez** [comment]
@ProfOak thanks, took your conftest as a fix

**Comment by ProfOak** [comment]
If you read the rest of the conversation, it sounds like we are going to go with a mock of Indexd instead of spawning an indexd subprocess.

**Comment by DrSpez** [comment]
closed in favor of #94

**Pull request closed without merging**
