### PR TITLE
fix(reqs): no need for git user in https installs

### PR DESCRIPTION
**Pull request by jbarno**
Description about what this pull request does.

Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.

### New Features
- Removes git@ in the https install urls?

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
Jenkins Build 2 : time taken 1 hr 0 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 3 : time taken 45 sec

**Comment by PlanXCyborg** [comment]
Jenkins Build 1 : time taken 11 sec
          Check the https://jenkins.planx-pla.net/job/perf-sheepdog/job/PR-242/1/display/redirect

**Comment by jbarno** [comment]
we forked anyway

**Pull request closed without merging**
